# **Numpy**

Segundo a [documentação oficial](https://numpy.org/doc/), NumPy é um pacote para computação científica em Python.  

---
## **Instalação**


A instalação do pocote pode ser feita usando um dos comandos abaixo: 

- `conda install numpy`, pode-se utilizar o [Conda](https://docs.conda.io/en/latest/) 
- `pip install numpy`, pode-se tambem ser utilizado o [Python Package Index (PyPI)](https://pypi.org/)

---
## **Importando o NumPy**

```python
import numpy as np
```

In [1]:
# ---
# seu código vai aqui
# ---
import numpy as np

---
## **Numpy Arrays**

> Para criar um numpy array podemos declarar uma lista e utilizá-la como parâmetro para a função array().

```python
list1 = [0,1,2,3]
```

In [2]:
# ---
# seu código vai aqui
# ---

```python
arr = np.array(list1)
```

In [3]:
# ---
# seu código vai aqui
# ---

💡 **Note que podemos criar uma matriz a partir de um cojunto de listas ou de arrays:**

```python
list1 = [0,1,2,3]
list2 = [4,5,6,7]
list3 = [8,9,10,11]
```

In [4]:
# ---
# seu código vai aqui
# ---

```python
mat = np.array([list1,list2,list3])
```

In [5]:
# ---
# seu código vai aqui
# ---

---
## **Inicializando valores dos arrays**

Funções para criar e inicializar arrays: 
- `.arange()`
- `.zeros()`
- `.ones()`
- `.linspace()` 
- `.eye()`

---
### 👉 **.arange()**

> Cria uma sequência de números entre um valor inicial, um valor final. Note que os valores intermediários podem ter o valor de incremento personalizado.

```python
# Ex 1.:
arr = [0, 1, ..., 10]

# Ex 2.:
arr = [0, 2, ..., 24]
```

Experimente criar um vetor com mais de 10 itens.

In [6]:
# ---
# seu código vai aqui
# ---

**Como pode ser visto na documentação, a sintaxe esperada é:**  
```python
arr = np.arange(valor_inicial, valor_final, valor_incrementado)
```
Logo, crie um array com 10 elementos:

In [7]:
# ---
# seu código vai aqui
# ---

💡 **Note que o primeiro valor "0" está incluído no array e que o último valor "10" não é incluído.**

Crie um `arr` com os valores: `[0, 2, ..., 64]`

In [8]:
# ---
# seu código vai aqui
# ---

---
### 👉 **.zeros() e .ones()**

> Tais funções criam arrays contendo apenas valores iguais a 0 (zero) ou 1 (um), respectivamente.

**As sintaxes esperadas são:**
- `arr_zeros = np.zeros((dim1, dim2, dim3, ...))`  
- `arr_ones = np.ones((dim1, dim2, dim3, ...))`

Crie um array com três elementos 0:

```python
np.zeros(num_elementos)
```

In [9]:
# ---
# seu código vai aqui
# ---

Crie uma matriz 5x5 preenchida com elementos 0:
```python
np.zeros((num_linhas, num_colunas))
```

In [10]:
# ---
# seu código vai aqui
# ---

Crie um array com três elementos 1:
```python
np.ones(num_elementos)
```

In [11]:
# ---
# seu código vai aqui
# ---

Crie uma matriz 3x3 preenchida com elementos 1:
```python
np.ones((num_linhas, num_colunas))
```

In [12]:
# ---
# seu código vai aqui
# ---

---
### 👉 **.linspace()**

> Cria valores igualmente espaçados em um determinado intervalo.

**A sintaxe esperada é:**
```python
np.linspace(inicio, fim, espaços)
```

Crie uma sequencia de 3 números entre 0 e 10, igualmente espaçados entre si:

```python
arr = np.linspace(0,10,3)
```

In [13]:
# ---
# seu código vai aqui
# ---

Criar uma sequencia de 15 números entre 0 e 10, igualmente espaçados entre si:
```python
arr = np.linspace(0,10,_)
```

In [14]:
# ---
# seu código vai aqui
# ---

---
### 👉 **.eye()**

> Cria uma matriz identidade, ou seja, uma matriz cuja diagonal principal tem valores 1, e todos os outros valores são 0.

**A sintaxe esperada é:**   

```python
np.eye(dimensão)
```

Crie uma matriz identidade de dimensões 4x4:

In [15]:
# ---
# seu código vai aqui
# ---

---
### 👉 Gerando números aleatórios com .random

- `random.seed(a)`:
  - Inicializa o gerador de números aleatórios.
  - Garante reprodutibilidade ao definir um estado inicial.

- `random.randint(valor_minimo, valor_maximo, tamanho)`:
  - Gera um número inteiro aleatório entre 0 e 10 (inclusive).

- `random.rand(tamanho)`:
  - Gera um número decimal aleatório entre 0 e 1 (distribuição uniforme).

- `random.randn(tamanho)`:
  - Gera um número decimal aleatório seguindo uma distribuição normal (média 0, desvio padrão 1).

In [16]:
np.random.seed(101)
np.random.randint(0, 10, 10)

array([1, 6, 7, 9, 8, 4, 8, 5, 0, 5])

In [17]:
np.random.seed(101)
np.random.rand(10)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166, 0.68527698,
       0.83389686, 0.30696622, 0.89361308, 0.72154386, 0.18993895])

In [18]:
np.random.seed(101)
np.random.randn(10)

array([ 2.70684984,  0.62813271,  0.90796945,  0.50382575,  0.65111795,
       -0.31931804, -0.84807698,  0.60596535, -2.01816824,  0.74012206])

---
## **Atributos e métodos de arrays**

**São funções e atributos intrínsicos dos arrays, considerados dados internos. Vejamos alguns exemplos a seguir.**

---
### 👉 **.reshape()**

> Altera as dimensões de um array, desde que as dimensões inicias e finais sejam compatíveis.

**A sintaxe esperada é:**   

```python
arr.reshape((dim1, dim2, dim3, ...))
```

Crie um array de 25 elementos:

```python
arr = np.arange(_)
```

In [19]:
# ---
# seu código vai aqui
# ---

Redimensione o array para um matriz de dimensoes 5x5:
```python
arr.reshape((_,_))
```

In [20]:
# ---
# seu código vai aqui
# ---

💡 Note, que algumas funções podem ser empilhadas em uma mesma linha como:
> `arr = np.arange(_).reshape((_,_))`

---
### 👉 **.max()**, **.min()**, **.argmax()** e **.argmin()**

> Retornam os valores máximo, mínimo, o índice do valor máximo e índice do valor mínimo de um array, respectivamete.

Crie um array com valores aleatórios. Utilize o seed com valor 101.

```python
arr = np.random.rand(10)
```

In [21]:
# ---
# seu código vai aqui
# ---

Informe o maior valor desse array:
```python
arr.max()
```

In [22]:
# ---
# seu código vai aqui
# ---

Informe o indice do elemento de maior valor do array, ou seja, a posição que ele ocupa no array:
```python
arr.argmax()
```

In [23]:
# ---
# seu código vai aqui
# ---

Informe o menor valor desse array:
```python
arr.min()
```

In [24]:
# ---
# seu código vai aqui
# ---

Informa o indice do elemento de menor valor do array, ou seja, a posição que ele ocupa no array:
```python
arr.argmin()
```

In [25]:
# ---
# seu código vai aqui
# ---

---
### 👉 **shape**

> Uma tupla que armazena as dimensões do array.

Gerando uma matriz aleatória:

In [26]:
m = np.random.randint(1, 10)
n = np.random.randint(1, 10)

mat = np.random.rand(m * n).reshape((m, n))
display(mat)

array([[0.78560176, 0.96548322, 0.23235366, 0.08356143],
       [0.60354842, 0.72899276, 0.27623883, 0.68530633]])

Visualize o formato dessa matriz em relação o numero de linhas (m) e colunas (n).

```python
mat.shape
```

In [27]:
# ---
# seu código vai aqui
# ---
mat.shape

(2, 4)

---
### 👉 **dtype()**

> Informa qual é o tipo de variável dos elementos do array.

Gerando uma array aleatória:

In [28]:
arr = np.random.rand(25)

Consultado o tipo de dado que é constituido esse array.

```python
arr.dtype
```

In [29]:
# ---
# seu código vai aqui
# ---

---
## **Seleção e indexação de numpy arrays**

---
### 👉 **Seleção por chaves**

> Como selecionar um ou mais elementos de um array.

Gerando uma array aleatória:

In [30]:
np.random.seed(101)
arr = np.random.rand(25)
display(arr)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166, 0.68527698,
       0.83389686, 0.30696622, 0.89361308, 0.72154386, 0.18993895,
       0.55422759, 0.35213195, 0.1818924 , 0.78560176, 0.96548322,
       0.23235366, 0.08356143, 0.60354842, 0.72899276, 0.27623883,
       0.68530633, 0.51786747, 0.04848454, 0.13786924, 0.18696743])

Como mostrar o elemento da 5ª posição:

```python
arr[5]
```

In [31]:
# ---
# seu código vai aqui
# ---

- mostra os elementos do intervalo desde até o segundo elemento até o quinto elemento
- note que o segundo elemento é incluído e o quinto elemento não é incluído

Mostre os elementos de um intervalo que comece no segundo elemento e termine no quinto elemento desse array.

```python
arr[2:5]
```

In [32]:
# ---
# seu código vai aqui
# ---

💡 Note que uns dos elementos estão ausentes, identifique e corrige o valor do intervalo do slice.

In [33]:
# ---
# seu código vai aqui
# ---

---
### 👉 ***Broadcasting***

> Realiza operações matemáticas para todos os elemento de um array.

Gerando uma array aleatória:

In [34]:
np.random.seed(101)
arr = np.random.randint(0, 10, 10)
display(arr)

array([1, 6, 7, 9, 8, 4, 8, 5, 0, 5])

Some uma constante a todos os elementos desse array:

```python
arr + 2
```

In [35]:
# ---
# seu código vai aqui
# ---

Multiplique uma constante a todos os elementos desse array:

```python
arr * 2
```

In [36]:
# ---
# seu código vai aqui
# ---

Subtraia uma constante a todos os elementos desse array:

```python
arr - 5
```

In [37]:
# ---
# seu código vai aqui
# ---

Divide uma constante a todos os elementos desse array:

```python
arr / 5
```
💡 Note que a divisão por zero gera um aviso e seu resultado é um NaN.

In [38]:
# ---
# seu código vai aqui
# ---

Eleve cada elemento desse array a uma constante.

```python
arr ** 2
```

In [39]:
# ---
# seu código vai aqui
# ---

---
# 🥳🥳🥳 Bom trabalho!